framework:
  website: hyperf.io
  version: 2.0

php_ext:
  - redis
  - swoole

before_command:
  - echo "swoole.use_shortname = 'Off'" >> /usr/local/etc/php/conf.d/docker-php-ext-swoole.ini

command: php sbin/hyperf.php start
